# .nixpacks.yml
providers:
  python:
    install:
      - pip install -r requirements.txt
    build:
      - python manage.py collectstatic --noinput
    start: |
      python manage.py migrate
      gunicorn ElectiveApp.ElectiveApp.wsgi --workers 3