# Generated by Django 5.2 on 2025-05-09 08:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="student",
            name="plain_password",
            field=models.CharField(default="default_password", max_length=128),
            preserve_default=False,
        ),
    ]
