# Generated by Django 5.2 on 2025-05-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_student_date_created_student_plain_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, max_length=20)),
                ("semester", models.IntegerField()),
                ("stream", models.CharField(max_length=50)),
                ("is_elective", models.BooleanField(default=False)),
            ],
        ),
    ]
