# Generated by Django 5.2 on 2025-05-11 18:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_electiveselection"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="electiveselection",
            options={
                "verbose_name": "Elective Selection",
                "verbose_name_plural": "Elective Selections",
            },
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Student", "verbose_name_plural": "Students"},
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"verbose_name": "Subject", "verbose_name_plural": "Subjects"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterField(
            model_name="electiveselection",
            name="selected_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the elective was selected."
            ),
        ),
        migrations.AlterField(
            model_name="electiveselection",
            name="student",
            field=models.ForeignKey(
                help_text="Student who selected the elective.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elective_selections",
                to="core.student",
            ),
        ),
        migrations.AlterField(
            model_name="electiveselection",
            name="subject",
            field=models.ForeignKey(
                help_text="Selected elective subject.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="selections",
                to="core.subject",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="date_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Timestamp when the student record was created.",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CS", "Computer Science"),
                    ("IT", "Information Technology"),
                    ("ECE", "Electronics and Communication"),
                ],
                help_text="Student's department.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_login_info_submitted",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the student has submitted initial info (department, semester).",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="plain_password",
            field=models.CharField(
                blank=True,
                help_text="Plain-text password for initial login (temporary storage).",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="roll",
            field=models.CharField(
                blank=True,
                help_text="Student's roll number, if assigned.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="semester",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Semester 1"),
                    ("2", "Semester 2"),
                    ("3", "Semester 3"),
                    ("4", "Semester 4"),
                    ("5", "Semester 5"),
                    ("6", "Semester 6"),
                    ("7", "Semester 7"),
                    ("8", "Semester 8"),
                ],
                help_text="Current semester of the student.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                help_text="Associated user account.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="year",
            field=models.IntegerField(
                blank=True, help_text="Academic year (e.g., 2023).", null=True
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Subject code (e.g., PCC-CS601).",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="is_elective",
            field=models.BooleanField(
                default=False, help_text="Indicates if the subject is an elective."
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(
                help_text="Name of the subject (e.g., Database Management Systems).",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="semester",
            field=models.IntegerField(
                help_text="Semester in which the subject is offered (1-8)."
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="stream",
            field=models.CharField(
                help_text="Stream or category (e.g., Core CS, PE Group 1, OE I).",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=255, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("student", "Student")],
                default="student",
                help_text="User's role in the system (admin or student).",
                max_length=10,
            ),
        ),
    ]
