# Generated by Django 5.2 on 2025-05-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_electiveselection_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="elective_finalized",
            field=models.BooleanField(
                default=False, help_text="If True it means the electives are finalized."
            ),
        ),
    ]
