# Generated by Django 5.2 on 2025-05-14 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_student_elective_finalized"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllocationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        help_text="Semester for which the allocation is made.",
                        max_length=10,
                    ),
                ),
                (
                    "stream",
                    models.CharField(
                        help_text="Elective group or stream (e.g., Professional Elective VI).",
                        max_length=50,
                    ),
                ),
                (
                    "is_match",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the chosen and allocated subjects match.",
                    ),
                ),
                (
                    "allocated_subject",
                    models.ForeignKey(
                        blank=True,
                        help_text="Subject allocated to the student for this stream.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allocated_in_allocations",
                        to="core.subject",
                    ),
                ),
                (
                    "chosen_subject",
                    models.ForeignKey(
                        blank=True,
                        help_text="Subject chosen by the student for this stream.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chosen_in_allocations",
                        to="core.subject",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student for whom the allocation is made.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocation_results",
                        to="core.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allocation Result",
                "verbose_name_plural": "Allocation Results",
                "unique_together": {("semester", "student", "stream")},
            },
        ),
    ]
