# Generated by Django 5.2 on 2025-05-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_allocationresult_is_match_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="roll",
            field=models.CharField(
                blank=True,
                help_text="Student's roll number, if assigned.",
                max_length=20,
                null=True,
            ),
        ),
    ]
